"""empty message

Revision ID: 18d07381b34f
Revises: 105ffcf956d8
Create Date: 2025-01-17 18:49:11.194713

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '18d07381b34f'
down_revision: Union[str, None] = '105ffcf956d8'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('authors', 'created_at',
               existing_type=postgresql.TIMESTAMP(),
               type_=sa.TIMESTAMP(timezone=True),
               nullable=False,
               existing_server_default=sa.text('CURRENT_TIMESTAMP'))
    op.create_index(op.f('ix_authors_id'), 'authors', ['id'], unique=False)
    op.alter_column('books', 'created_at',
               existing_type=postgresql.TIMESTAMP(),
               type_=sa.TIMESTAMP(timezone=True),
               nullable=False,
               existing_server_default=sa.text('CURRENT_TIMESTAMP'))
    op.create_index(op.f('ix_books_id'), 'books', ['id'], unique=False)
    op.alter_column('borrowers', 'created_at',
               existing_type=postgresql.TIMESTAMP(),
               type_=sa.TIMESTAMP(timezone=True),
               nullable=False,
               existing_server_default=sa.text('CURRENT_TIMESTAMP'))
    op.create_index(op.f('ix_borrowers_id'), 'borrowers', ['id'], unique=False)
    op.add_column('transactions', sa.Column('returned_date', sa.TIMESTAMP(timezone=True), nullable=True))
    op.alter_column('transactions', 'transaction_date',
               existing_type=postgresql.TIMESTAMP(),
               type_=sa.TIMESTAMP(timezone=True),
               nullable=False,
               existing_server_default=sa.text('CURRENT_TIMESTAMP'))
    op.alter_column('transactions', 'due_date',
               existing_type=sa.DATE(),
               type_=sa.TIMESTAMP(timezone=True),
               existing_nullable=False)
    op.create_index(op.f('ix_transactions_id'), 'transactions', ['id'], unique=False)
    op.drop_column('transactions', 'return_date')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('transactions', sa.Column('return_date', sa.DATE(), autoincrement=False, nullable=True))
    op.drop_index(op.f('ix_transactions_id'), table_name='transactions')
    op.alter_column('transactions', 'due_date',
               existing_type=sa.TIMESTAMP(timezone=True),
               type_=sa.DATE(),
               existing_nullable=False)
    op.alter_column('transactions', 'transaction_date',
               existing_type=sa.TIMESTAMP(timezone=True),
               type_=postgresql.TIMESTAMP(),
               nullable=True,
               existing_server_default=sa.text('CURRENT_TIMESTAMP'))
    op.drop_column('transactions', 'returned_date')
    op.drop_index(op.f('ix_borrowers_id'), table_name='borrowers')
    op.alter_column('borrowers', 'created_at',
               existing_type=sa.TIMESTAMP(timezone=True),
               type_=postgresql.TIMESTAMP(),
               nullable=True,
               existing_server_default=sa.text('CURRENT_TIMESTAMP'))
    op.drop_index(op.f('ix_books_id'), table_name='books')
    op.alter_column('books', 'created_at',
               existing_type=sa.TIMESTAMP(timezone=True),
               type_=postgresql.TIMESTAMP(),
               nullable=True,
               existing_server_default=sa.text('CURRENT_TIMESTAMP'))
    op.drop_index(op.f('ix_authors_id'), table_name='authors')
    op.alter_column('authors', 'created_at',
               existing_type=sa.TIMESTAMP(timezone=True),
               type_=postgresql.TIMESTAMP(),
               nullable=True,
               existing_server_default=sa.text('CURRENT_TIMESTAMP'))
    # ### end Alembic commands ###
