"""empty message

Revision ID: 7a0521d3c0a2
Revises: 18d07381b34f
Create Date: 2025-01-19 15:06:42.314418

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '7a0521d3c0a2'
down_revision: Union[str, None] = '18d07381b34f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('books', 'title',
               existing_type=sa.VARCHAR(length=200),
               nullable=False)
    op.add_column('transactions', sa.Column('return_date', sa.TIMESTAMP(timezone=True), nullable=True))
    op.drop_column('transactions', 'returned_date')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('transactions', sa.Column('returned_date', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=True))
    op.drop_column('transactions', 'return_date')
    op.alter_column('books', 'title',
               existing_type=sa.VARCHAR(length=200),
               nullable=True)
    # ### end Alembic commands ###
